imports:
    - { resource: services/service_aliases.yml }
    - { resource: services/controllers.yml }
    - { resource: services/tabs.yml }
    - { resource: services/menu.yml }
    - { resource: services/application_config.yml }

parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    EzSystems\EzPlatformAdminUi\Service\TrashService\TrashService: '@EzSystems\EzPlatformAdminUi\Service\TrashService'

    EzSystems\EzPlatformAdminUi\Service\Role\RoleServiceInterface: '@EzSystems\EzPlatformAdminUi\Service\Role\RoleService'

    EzSystems\EzPlatformAdminUiBundle\ParamConverter\:
        resource: "../../ParamConverter/*"
        public: true
        tags:
            - { name: 'request.param_converter' }

    EzSystems\EzPlatformAdminUi\EventListener\:
        resource: "../../../lib/EventListener/*"
        public: true
        tags:
            - { name: kernel.event_subscriber }

    EzSystems\EzPlatformAdminUi\EventListener\RequestListener:
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            - { name: kernel.event_subscriber }

    EzSystems\EzPlatformAdminUi\Service\:
        resource: '../../../lib/Service/*'
        public: true

    EzSystems\EzPlatformAdminUi\Service\ContentTypeService:
        arguments:
            $prioritizedLanguages: '$languages$'

    EzSystems\EzPlatformAdminUi\Form\Type\:
        resource: '../../../lib/Form/Type'

    EzSystems\EzPlatformAdminUi\Form\DataMapper\:
        resource: '../../../lib/Form/DataMapper'

    EzSystems\EzPlatformAdminUi\Form\Type\Policy\PolicyChoiceType:
        arguments:
            $policyMap: "%ezpublish.api.role.policy_map%"

    EzSystems\EzPlatformAdminUi\UI\Dataset\Factory: ~
    EzSystems\EzPlatformAdminUi\UI\Value\ValueFactory:
        lazy: true
        tags:
            - { name: form.type }

    EzSystems\EzPlatformAdminUi\Form\Factory\FormFactory: ~

    EzSystems\EzPlatformAdminUi\ApplicationConfig\Providers\ContentTypeMappings:
        arguments:
            $locationMappings: "%ezplatform.multifile_upload.location.mappings%"
            $defaultMappings: "%ezplatform.multifile_upload.location.default_mappings%"
            $fallbackContentType: "%ezplatform.multifile_upload.fallback_content_type%"
            $maxFileSize: "%ez_systems.multifile_upload.max_file_size%"
        tags:
            - { name: ezplatform.admin_ui.config_provider, key: 'multiFileUpload' }

    EzSystems\EzPlatformAdminUi\Notification\FlashBagNotificationHandler:
        arguments:
            $flashBag: "@=service('session').getFlashBag()"

    EzSystems\EzPlatformAdminUi\Notification\NotificationHandlerInterface: '@EzSystems\EzPlatformAdminUi\Notification\FlashBagNotificationHandler'
